### ISSUE TITLE
`@Context` Injection Issue in JAX-RS Test

### ISSUE THREAD

**Issue by apaapapapapa** [cdi-unit/cdi-unit#548]
# `@Context` Injection Issue in JAX-RS Test

Hi,  

I'm implementing a JAX-RS test using CDI-Unit, 
but I'm facing an issue where a field annotated with `@Context` does not receive the mocked object properly. 

When I run the test, `headers.getRequestHeader("User-Agent")` returns `null` , causing the test failing.
However, when I replace `@Context` with `@Inject`, the test passes successfully.  

Here is my class:  

```java
package com.example.web;

import java.util.List;
import jakarta.enterprise.context.RequestScoped;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.*;

@RequestScoped
@Path("/example")
public class ExampleWebService {
  
    @Context
    HttpHeaders headers;

    @GET
    @Path("/client-info")
    @Produces(MediaType.APPLICATION_JSON)
    public Response getClientInfo() {
        List<String> userAgentList = headers.getRequestHeader("User-Agent");
        String userAgent = userAgentList != null && !userAgentList.isEmpty() ? userAgentList.get(0) : "Unknown";
        return Response.ok("{\"userAgent\": \"" + userAgent + "\"}").build();
    }
}
```
And here is the test class:
```java
package com.example.web;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.when;

import java.util.Collections;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;

import io.github.cdiunit.InRequestScope;
import io.github.cdiunit.jaxrs.SupportJaxRs;
import io.github.cdiunit.junit5.CdiJUnit5Extension;
import jakarta.ws.rs.core.Response;
import jakarta.enterprise.inject.Produces;
import jakarta.inject.Inject;
import jakarta.ws.rs.core.HttpHeaders;

@ExtendWith({CdiJUnit5Extension.class})
@SupportJaxRs
class ExampleWebServiceTest {

    @Inject
    ExampleWebService exampleWebService;

    @Produces
    @Mock
    HttpHeaders mockHeaders;

    @InRequestScope
    @Test
    void testGetClientInfo() {
        when(mockHeaders.getRequestHeader("User-Agent")).thenReturn(Collections.singletonList("Test-Agent"));

        Response response = exampleWebService.getClientInfo();

        assertNotNull(response);
        assertEquals(200, response.getStatus());
        assertEquals("{\"userAgent\": \"Test-Agent\"}", response.getEntity().toString());
    }
}
```
When I run the test, I get the following failure:

```log
expected: <{"userAgent": "Test-Agent"}> but was: <{"userAgent": "Unknown"}>
```

However, if I change:

```java
@Context
HttpHeaders headers;
```

to:

```java
@Inject
HttpHeaders headers;
```

the test works correctly.

**Is this an issue with my implementation, or is there something missing in CDI-Unit's handling of @Context injection?**

I'm using the following version of CDI-Unit:
```xml
<dependency>
    <groupId>io.github.cdi-unit</groupId>
    <artifactId>cdi-unit</artifactId>
    <version>5.0.0-EA7</version>
    <scope>test</scope>
</dependency>
```
And my environment:
```yml
PS C:\Workspaces\weld-testing> mvn -v
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: C:\Program Files\Maven\apache-maven-3.9.6
Java version: 17.0.9, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17
Default locale: ja_JP, platform encoding: MS932
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
PS C:\Workspaces\weld-testing> 
```

Hear is my [repository](https://github.com/apaapapapapa/weld-testing/blob/feat-jaxrs/src/test/java/com/example/web/ExampleWebServiceTest.java). 

Thank you for your great support!
